spring:
  datasource:
    url: jdbc:sqlserver://202.118.24.59;database=course_schedule;encrypt=false;
    username: 
    password: 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring:
#  datasource:
#   url: jdbc:mysql://localhost:3306/neusoftmall?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#   username: root
#   password: 123456
#   driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
